sudo: required
dist: trusty
language: node_js
node_js:
- 14
cache:
- yarn
git:
  depth: 1
script:
- yarn lint
- yarn test:coverage
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
- yarn build
notifications:
  email:
    recipients:
    - particle4dev@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: npm
  email: particle4dev@gmail.com
  on:
    tags: true
    repo: particle4dev/slugify
  api_token:
    secure: b+9FQci4EKRtRpT9+JUvQsZKhrAGSk8GfOZGaO1NQ68LnHYVnbXiPBdoLj7RxcN0JYzTASTNy2uxFvbH7j1+ejIGw/siM/MXcuDukIljSwffUYGFh/MuaIuQp9VYTd2oVA+KoYnyOW3g9YTzjBSa3q/xsJnPMYOygZL4tQKXzu0tyMdvt+inpMWD/sZg6cAKqozNHdVGmOMN/fD8RGkY8MT4WcbF0t8MEnZxBme5yl0g5TWLzIYkq4bJKzv3voIJuv6IJaZmbzhUe/YfZn1pCG5+01lTX/YmAvQ2qPgL4QaBbRteltJtBb+GOZ4AC8F2WMW/x3xq0cDVhSgEc1S07wPJfDhkhgu0GDogKaWSqhJh2r9U0D16niiyDRZRB/ozYHUYuPhnXkVr1pmLs9aChtPZW5YxUl7gQom0w74UDqrn3ezHSCKVmEQGvXAnTuJIWMeLlfTAuMeVf0lT/bDYc5FcsgoUOJkOYCIEZOv518dCMcgOhHub3Cy0HYMO9Nw9Zje4F8I25YJAof+0Cph3ZX5cHIA6sTUkvdUkEJ+bJb7ArG3r0Udytr5guD4vLXoYdhjp7iIrx0xq7x2ztVxGoxVK6DP25+jCHregRuH7+Sitg5+NRCtRgHYXKeDlfMOlyUtWR2RTXLT+nTfEmS5EAZ2051d78rBi4ZSdj7mlKzs=
  skip_cleanup: 'true'
